export const editButton = document.querySelector('.button_type_edit');
export const addButton = document.querySelector('.button_type_add');
export const nameInput = document.querySelector('.form__item_type_name');
export const jobInput = document.querySelector('.form__item_type_job');
export const formElement = document.querySelector('.form_type_edit');
export const newCardElement = document.querySelector('.form_type_add');
export const updateAvatarForm = document.querySelector('.form_type_avatar-update');
export const updatedAvatar = document.querySelector('.profile__avatar');
export const updateAvatar = document.querySelector('.profile__overlay');
export const userName = document.querySelector('.profile__name');
export const userJob = document.querySelector('.profile__job');
export const cardSelector = document.querySelector('.template');
export let userId;
